/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2021-09-23 05:53:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.helper.UserModel;

public final class leftmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.helper.UserModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<nav class=\"side-navbar mCustomScrollbar _mCS_1\">\r\n");
      out.write("\r\n");

	UserModel um=null;
	if(session.getAttribute("USER_MODEL")==null){ 
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\twindow.location.href='");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp';\r\n");
      out.write("\t\t</script>");

}else{
	um=(UserModel)session.getAttribute("USER_MODEL");
}
    
      out.write("\r\n");
      out.write("         \r\n");
      out.write("\t<div id=\"mCSB_1\"\r\n");
      out.write("\t\tclass=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\"\r\n");
      out.write("\t\tstyle=\"max-height: none;\" tabindex=\"0\">\r\n");
      out.write("\t\t<div id=\"mCSB_1_container\" class=\"mCSB_container\"\r\n");
      out.write("\t\t\tstyle=\"position: relative; top: 0; left: 0;\" dir=\"ltr\">\r\n");
      out.write("\t\t\t<div class=\"side-navbar-wrapper\">\r\n");
      out.write("\t\t\t\t<!-- Sidebar Header    -->\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"sidenav-header d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t\t<!-- User Info-->\r\n");
      out.write("\t\t\t\t\t<div class=\"sidenav-header-inner text-center\">\r\n");
      out.write("<!-- \t\t\t\t\t\t<img src=\"img/avatar-7.jpg\" alt=\"person\" -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\tclass=\"img-fluid rounded-circle mCS_img_loaded\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t ");
if(um!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"h5\"> \r\n");
      out.write("\t\t\t\t\t\t   ");
if(um!=null){ 
      out.write("\r\n");
      out.write("                   Hello ");
      out.print(um.getUsername() );
      out.write("</h2>\r\n");
      out.write("                      ");
}else{ 
      out.write("  \r\n");
      out.write("               \t<h2 class=\"h5\">  Hello Guest </h2> \r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span> ");
      out.print(um.getRegion() );
      out.write("\r\n");
      out.write("                    ");
} 
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Small Brand information, appears on minimized sidebar-->\r\n");
      out.write("\t\t\t\t\t<div class=\"sidenav-header-logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"index.html\" class=\"brand-small text-center\"> <strong>B</strong><strong\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-primary\">D</strong></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Sidebar Navigation Menus-->\r\n");
      out.write("\t\t\t\t<div class=\"main-menu\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"sidenav-heading\">Main</h5>\r\n");
      out.write("\t\t\t\t\t<ul id=\"side-main-menu\" class=\"side-menu list-unstyled\">\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t\t</a></li> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t\t</a></li> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t\t</a></li> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t\t</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"mCSB_1_scrollbar_vertical\"\r\n");
      out.write("\t\t\tclass=\"mCSB_scrollTools mCSB_1_scrollbar mCS-light mCSB_scrollTools_vertical\"\r\n");
      out.write("\t\t\tstyle=\"display: block;\">\r\n");
      out.write("\t\t\t<div class=\"mCSB_draggerContainer\">\r\n");
      out.write("\t\t\t\t<div id=\"mCSB_1_dragger_vertical\" class=\"mCSB_dragger\"\r\n");
      out.write("\t\t\t\t\tstyle=\"position: absolute; min-height: 30px; height: 330px; top: 0px; display: block; max-height: 479px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mCSB_dragger_bar\" style=\"line-height: 30px;\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mCSB_draggerRail\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
