/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2020-01-22 11:55:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.constant.ServerConstants;
import com.amazonaws.regions.Regions;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.constant.ServerConstants");
    _jspx_imports_classes.add("com.amazonaws.regions.Regions");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/header.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"page login-page\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"form-outer text-center d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t<div class=\"form-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo text-uppercase\">\r\n");
      out.write("\t\t\t\t\t\t<span>AWS</span><strong class=\"text-primary\">Cloudability</strong>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form class=\"text-left form-validate\" id=\"contact-form\" action=\"javascript:fnSubmit();\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"fname\" type=\"text\" name=\"fname\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired data-msg=\"Please enter your first name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-material\"> <label for=\"register-username\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"label-material\">First Name</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"lname\" type=\"text\" name=\"lname\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired data-msg=\"Please enter your last name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-material\"> <label for=\"register-username\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"label-material\">Last Name</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"phoneno\" type=\"text\" name=\"phoneno\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired data-msg=\"Please enter your Mobile Number\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-material\"> <label for=\"register-username\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"label-material\">Contact Number</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"username\" type=\"text\" name=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired data-msg=\"Please enter your user name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-material\"> <label for=\"register-username\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"label-material\">User Name</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"userpass\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"userpass\" required\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-msg=\"Please enter your password\" class=\"input-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"register-password\" class=\"label-material\">Password\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"cuserpass\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"cuserpass\" required\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-msg=\"Please enter your password\" class=\"input-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"register-password\" class=\"label-material\">Re-Enter Password\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"accessKey\" type=\"text\" name=\"accessKey\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired data-msg=\"Please enter your user name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-material\"> <label for=\"register-username\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"label-material\">Access Key</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group-material\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"accessSecret\" type=\"text\" name=\"accessSecret\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired data-msg=\"Please enter your user name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-material\"> <label for=\"register-username\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"label-material\">Access Secret</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"register\" type=\"submit\" value=\"Register\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<small>Already have an account? </small><a onclick=\"fnLogin()\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"Login\" class=\"signup\">Login</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/footer_inc.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function fnLogin(){\r\n");
      out.write("\t\r\n");
      out.write("\twindow.location.href='");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp';\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fnSubmit(){\r\n");
      out.write("\t\r\n");
      out.write("\tif($('#userpass').val()!=$('#cuserpass').val()){\r\n");
      out.write("\t\talert('Password and confirm password do not match!');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t var str = $( \"#contact-form\" ).serialize();\r\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=registerNewUser\",\r\n");
      out.write("\t\t\tstr,\r\n");
      out.write("\t\t\tfunction(data) {\r\n");
      out.write("data=$.trim(data);  \r\n");
      out.write("if(data.indexOf('Successfully')!=-1){\r\n");
      out.write("\talert(data);\r\n");
      out.write("\t$('#contact-form')[0].reset();\r\n");
      out.write("\twindow.location.href='");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp';\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
